version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: casaoferta-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: casaoferta
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: casaoferta-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_NAME: casaoferta
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_DIALECT: mysql
      PORT: 3000

  frontend:
    build: ./frontend
    container_name: casaoferta-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: